[build]
    functions = "functions"

[dev]
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*" # you can configure the correct paths here
  [headers.values]
    access-control-allow-origin = "*" 